#!/bin/sh
rm -rf  /lib/modules/5.4.142-gc19da14f4040-dirty/build
cd /lib/modules/5.4.142-gc19da14f4040-dirty/
ln -sf /usr/src/linux-headers-5.4.142-gc19da14f4040-dirty-arm64/ build

cd /usr/src/linux-headers-5.4.142-gc19da14f4040-dirty-common/
ln -sf ../linux-headers-5.4.142-gc19da14f4040-dirty-arm64/Makefile

cd /usr/src/linux-headers-5.4.142-gc19da14f4040-dirty-arm64/arch/arm64/
ln -sf /usr/src/linux-headers-5.4.142-gc19da14f4040-dirty-common/arch/arm64/kernel/
ln -sf /usr/src/linux-headers-5.4.142-gc19da14f4040-dirty-common/arch/arm64/Kbuild 
ln -sf /usr/src/linux-headers-5.4.142-gc19da14f4040-dirty-common/arch/arm64/Makefile 

cd /usr/src/linux-headers-5.4.142-gc19da14f4040-dirty-arm64/include
ln -sf /usr/local/src/linux-imx/include/config/auto.conf config/auto.conf
ln -sf /usr/src/linux-headers-5.4.142-gc19da14f4040-dirty-common/include/clocksource 
ln -sf /usr/src/linux-headers-5.4.142-gc19da14f4040-dirty-common/include/asm-generic
ln -sf /usr/local/src/linux-imx/include/uapi/
ln -sf /usr/local/src/linux-imx/include/linux/ 

cd /usr/src/linux-headers-5.4.142-gc19da14f4040-dirty-arm64/
ln -sf ../../lib/linux-kbuild-5.4.142-gc19da14f4040-dirty/scripts/
cd /usr/src/linux-headers-5.4.142-gc19da14f4040-dirty-common
ln -sf ../../lib/linux-kbuild-5.4.142-gc19da14f4040-dirty/scripts/
ln -sf ../linux-headers-5.4.142-gc19da14f4040-dirty-arm64/Makefile

