#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
    update-alternatives --install \
	/lib/firmware/regulatory.db regulatory.db /lib/firmware/regulatory.db-debian 100 \
	--slave /lib/firmware/regulatory.db.p7s regulatory.db.p7s /lib/firmware/regulatory.db.p7s-debian
    update-alternatives --install \
	/lib/firmware/regulatory.db regulatory.db /lib/firmware/regulatory.db-upstream 50 \
	--slave /lib/firmware/regulatory.db.p7s regulatory.db.p7s /lib/firmware/regulatory.db.p7s-upstream
fi


